### ISSUE TITLE
Setup Deck.GL Heatmap example with custom heatmap points

### ISSUE THREAD

**Issue by OmarShehata** [Edgar127/Onboarding#1]
@Edgar127 @ll299 so far you have been able to create a heatmap visualization with a custom set of points using Maplibre. We want to create one with Deck.GL so that we can reproduce the problem & try to fix it.

To do this:

1. Confirm you can one of the **existing** Deck.GL examples, like here: https://github.com/visgl/deck.gl/tree/master/examples/layer-browser
2. Modify this example to make it load a heatmap, like in this example: https://deck.gl/docs/api-reference/aggregation-layers/heatmap-layer
3. Make it load the heatmap from a custom set of points (ideally from a geojson file or can be from a list of points you put in the same code file)

Finally, take a screenshot and post it here.

**Comment by Edgar127** [comment]
<img width="1439" alt="Screenshot 2023-07-10 at 2 12 39 PM" src="https://github.com/Edgar127/Onboarding/assets/105250463/f8467fc1-0595-4c58-a524-1554a48b7411">
