### ISSUE TITLE
Make your first change to the Deck.GL Source Code

### ISSUE THREAD

**Issue by OmarShehata** [Edgar127/Onboarding#2]
Once you've finished this task https://github.com/Edgar127/Onboarding/issues/1, you will now have a way to see the heatmap drawn in Deck.GL. The next step is to make a change to the source code, and confirm the change appears.

1. Make a change by adding `console.log("Hello!")` in this line: https://github.com/visgl/deck.gl/blob/master/modules/aggregation-layers/src/heatmap-layer/heatmap-layer.ts#L63
2. Then run your example (like with the instructions here https://github.com/visgl/deck.gl/tree/master/examples/layer-browser) and see if your "Hello" prints out in the console

If this works, try making a functional change (something that will change how the heatmap looks). Some ideas:

* Change this line https://github.com/visgl/deck.gl/blob/master/modules/aggregation-layers/src/heatmap-layer/triangle-layer-fragment.glsl.ts#L57 to the following:

```glsl
gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0);
```

This should make the heatmap layer all red

**Comment by Edgar127** [comment]
<img width="1436" alt="Screenshot 2023-07-10 at 2 11 07 PM" src="https://github.com/Edgar127/Onboarding/assets/105250463/fc7aeea5-f89b-4fba-9561-04655b659e5b">

**Comment by OmarShehata** [comment]
Looks great, thanks Edgar!
